[build]
  command = "npx prisma migrate deploy && npx prisma generate && npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Redirect all server-side requests to Netlify Functions
[[redirects]]
  from = "/api/qr/generate"
  to = "/.netlify/functions/qr-generate"
  status = 200

# QR delete function - no redirect needed as frontend calls /.netlify/functions/qr-delete directly
# [[redirects]]
#   from = "/api/qr/*/delete"  
#   to = "/.netlify/functions/qr-delete"
#   status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# QR redirect handling - Fixed routing (must be before SPA fallback)
[[redirects]]
  from = "/r/:shortId"
  to = "/.netlify/functions/qr-redirect?shortId=:shortId"
  status = 200

# SPA fallback for client-side routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.stripe.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"